[package]
name = "webcrust"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
maud = "*"

[profile.release]
strip = true
lto = true